"""
Music Atlas - Scaled 550+ Artist Universe Generator.
Generates comprehensive global catalog across 11 musical sectors,
providing realistic popularity distributions, follower counts,
rich sub-genres, and seed metadata.
"""

import re
import json

def slugify(text: str) -> str:
    s = text.lower()
    s = re.sub(r'[^a-z0-9]+', '_', s).strip('_')
    return s

def build_artist(name, macro, subgenres, pop, followers, top_track=None):
    slug = slugify(name)
    return {
        "id": slug,
        "name": name,
        "macro_genre": macro,
        "genres": subgenres,
        "popularity": int(pop),
        "followers": int(followers),
        "top_track": top_track or f"{name}'s Top Hit",
        "preview_url": "",
        "spotifyUrl": f"https://open.spotify.com/search/{name.replace(' ', '%20')}",
        "image": ""
    }

def get_550_artist_catalog():
    artists = []

    # 1. HIP-HOP & RAP (~65 artists)
    rap_data = [
        ("Drake", ["canadian hip hop", "melodic rap", "pop rap"], 96, 89000000, "God's Plan"),
        ("Kendrick Lamar", ["conscious hip hop", "west coast rap", "hip hop"], 95, 32000000, "HUMBLE."),
        ("Travis Scott", ["houston rap", "trap", "hip hop"], 95, 36000000, "SICKO MODE"),
        ("21 Savage", ["atl hip hop", "trap", "gangster rap"], 91, 21000000, "Bank Account"),
        ("Future", ["atl hip hop", "southern hip hop", "trap"], 92, 19000000, "Mask Off"),
        ("Metro Boomin", ["rap", "trap", "hip hop producer"], 90, 14000000, "Creepin'"),
        ("Kanye West", ["chicago rap", "hip hop", "rap"], 94, 25000000, "Stronger"),
        ("Eminem", ["detroit hip hop", "hip hop", "rap"], 93, 88000000, "Lose Yourself"),
        ("J. Cole", ["conscious hip hop", "hip hop", "north carolina rap"], 90, 24000000, "No Role Modelz"),
        ("Lil Baby", ["atl hip hop", "trap", "southern rap"], 88, 16000000, "Drip Too Hard"),
        ("Gunna", ["atl hip hop", "melodic rap", "trap"], 87, 8500000, "fukumean"),
        ("Playboi Carti", ["rage rap", "atl hip hop", "trap"], 90, 12000000, "Magnolia"),
        ("Lil Uzi Vert", ["melodic rap", "philly rap", "trap"], 89, 18000000, "XO Tour Llif3"),
        ("A$AP Rocky", ["east coast hip hop", "harlem rap", "trap"], 88, 17000000, "Praise The Lord"),
        ("Tyler, The Creator", ["alternative hip hop", "hip hop", "rap"], 91, 19000000, "EARFQUAKE"),
        ("Mac Miller", ["pittsburgh rap", "hip hop", "conscious rap"], 87, 15000000, "Self Care"),
        ("Juice WRLD", ["chicago rap", "emo rap", "melodic rap"], 89, 31000000, "Lucid Dreams"),
        ("XXXTENTACION", ["emo rap", "miami hip hop", "cloud rap"], 88, 43000000, "SAD!"),
        ("Post Malone", ["dfw rap", "melodic rap", "pop rap"], 93, 44000000, "Circles"),
        ("Denzel Curry", ["florida rap", "underground hip hop", "hardcore rap"], 81, 3200000, "Ultimate"),
        ("JID", ["atl hip hop", "conscious hip hop", "southern rap"], 83, 3900000, "Surround Sound"),
        ("Baby Keem", ["hip hop", "west coast rap", "trap"], 82, 3800000, "family ties"),
        ("Central Cee", ["uk drill", "uk hip hop", "melodic drill"], 86, 6100000, "Doja"),
        ("Young Thug", ["atl hip hop", "trap", "melodic rap"], 87, 12000000, "Hot"),
        ("Kid Cudi", ["alternative hip hop", "cleveland rap", "neo-psychedelic"], 84, 1100000, "Day 'N' Nite"),
        ("Lil Wayne", ["new orleans rap", "southern hip hop", "trap"], 88, 18000000, "A Milli"),
        ("Snoop Dogg", ["g funk", "gangster rap", "west coast rap"], 86, 1600000, "Drop It Like It's Hot"),
        ("50 Cent", ["east coast hip hop", "gangster rap", "queens hip hop"], 85, 17000000, "In Da Club"),
        ("Jay-Z", ["east coast hip hop", "gangster rap", "brooklyn rap"], 86, 12000000, "Empire State of Mind"),
        ("Pusha T", ["virginia hip hop", "coke rap", "hip hop"], 77, 2400000, "Diet Coke"),
        ("Freddie Gibbs", ["indiana rap", "gangster rap", "underground hip hop"], 76, 1400000, "1985"),
        ("Joey Bada$$", ["brooklyn rap", "conscious hip hop", "boom bap"], 78, 2900000, "TEMPTATION"),
        ("Cordae", ["conscious hip hop", "dmv rap", "hip hop"], 75, 2100000, "RNP"),
        ("Vince Staples", ["cali rap", "alternative hip hop", "west coast rap"], 77, 1900000, "Norf Norf"),
        ("Ski Mask The Slump God", ["florida rap", "underground hip hop", "trap"], 81, 6800000, "Catch Me Outside"),
        ("Trippie Redd", ["emo rap", "melodic rap", "trap"], 83, 14000000, "Topanga"),
        ("Don Toliver", ["houston rap", "melodic rap", "trap soul"], 89, 7800000, "No Idea"),
        ("Roddy Ricch", ["cali rap", "melodic rap", "trap"], 82, 11000000, "The Box"),
        ("Polo G", ["chicago rap", "melodic drill", "trap"], 84, 13000000, "RAPSTAR"),
        ("Lil Tjay", ["bronx drill", "melodic rap", "nyc rap"], 82, 8900000, "Calling My Phone"),
        ("Lil Durk", ["chicago drill", "chicago rap", "trap"], 85, 8700000, "All My Life"),
        ("Chief Keef", ["chicago drill", "trap", "drill"], 83, 5400000, "Love Sosa"),
        ("Jack Harlow", ["pop rap", "louisville hip hop", "trap"], 85, 8900000, "First Class"),
        ("Ice Spice", ["bronx drill", "pop rap", "drill"], 84, 5200000, "Munch"),
        ("Megan Thee Stallion", ["houston rap", "trap", "pop rap"], 87, 14000000, "Savage"),
        ("Cardi B", ["bronx hip hop", "pop rap", "trap"], 87, 26000000, "Bodak Yellow"),
        ("Nicki Minaj", ["hip pop", "pop rap", "queens hip hop"], 89, 36000000, "Super Bass"),
        ("Doja Cat", ["dance pop", "pop rap", "r&b"], 90, 31000000, "Paint The Town Red"),
        ("GloRilla", ["memphis hip hop", "southern rap", "trap"], 81, 2400000, "TGIF"),
        ("Sexyy Red", ["st louis rap", "trap", "southern hip hop"], 80, 1800000, "SkeeYee"),
        ("Coi Leray", ["pop rap", "trap", "melodic rap"], 78, 3100000, "Players"),
        ("Dave", ["uk hip hop", "london rap", "conscious hip hop"], 83, 4200000, "Sprinter"),
        ("Stormzy", ["grime", "uk hip hop", "london rap"], 80, 3800000, "Vossi Bop"),
        ("Skepta", ["grime", "uk hip hop", "drill"], 78, 2600000, "Praise The Lord"),
        ("Little Simz", ["conscious hip hop", "uk hip hop", "experimental rap"], 76, 1600000, "Gorilla"),
        ("Loyle Carner", ["conscious hip hop", "uk alternative hip hop", "jazz rap"], 74, 980000, "Ottolenghi"),
        ("Nas", ["east coast hip hop", "golden age", "queens hip hop"], 83, 6200000, "N.Y. State of Mind"),
        ("Biggie Smalls", ["east coast hip hop", "brooklyn rap", "gangster rap"], 82, 10000000, "Juicy"),
        ("2Pac", ["west coast rap", "g funk", "gangster rap"], 84, 15000000, "California Love"),
        ("DMX", ["hardcore hip hop", "east coast rap", "rough riders"], 79, 7200000, "Ruff Ryders' Anthem"),
        ("Outkast", ["atl hip hop", "dirty south rap", "southern hip hop"], 81, 6500000, "Ms. Jackson"),
        ("Wu-Tang Clan", ["east coast hip hop", "hardcore hip hop", "staten island"], 78, 4800000, "C.R.E.A.M."),
        ("A Tribe Called Quest", ["jazz rap", "conscious hip hop", "east coast hip hop"], 76, 3200000, "Can I Kick It?"),
        ("MF DOOM", ["alternative hip hop", "underground hip hop", "abstract hip hop"], 79, 3600000, "Rapp Snitch Knishes"),
        ("Action Bronson", ["queens hip hop", "underground rap", "boom bap"], 72, 1100000, "Baby Blue")
    ]
    for n, sg, p, f, tt in rap_data:
        artists.append(build_artist(n, "Hip-Hop / Rap", sg, p, f, tt))

    # 2. POP (~65 artists)
    pop_data = [
        ("Taylor Swift", ["pop", "country pop", "art pop"], 100, 115000000, "Cruel Summer"),
        ("Billie Eilish", ["art pop", "electropop", "indie pop"], 96, 95000000, "BIRDS OF A FEATHER"),
        ("Ariana Grande", ["dance pop", "pop", "r&b"], 94, 98000000, "we can't be friends"),
        ("Dua Lipa", ["dance pop", "pop", "nu-disco"], 92, 45000000, "Levitating"),
        ("Olivia Rodrigo", ["pop", "pop punk", "indie pop"], 93, 41000000, "vampire"),
        ("Sabrina Carpenter", ["dance pop", "pop"], 95, 29000000, "Espresso"),
        ("Chappell Roan", ["synth pop", "indie pop", "alt-pop"], 93, 14000000, "Good Luck, Babe!"),
        ("Charli xcx", ["hyperpop", "electropop", "dance pop"], 91, 7400000, "360"),
        ("Harry Styles", ["pop", "pop rock", "indie pop"], 91, 48000000, "As It Was"),
        ("Katy Perry", ["dance pop", "pop"], 86, 34000000, "Teenage Dream"),
        ("Rihanna", ["barbadian pop", "pop", "urban contemporary"], 90, 61000000, "Diamonds"),
        ("Justin Bieber", ["canadian pop", "pop", "dance pop"], 91, 78000000, "Peaches"),
        ("Shawn Mendes", ["canadian pop", "pop", "singer-songwriter"], 85, 43000000, "Treat You Better"),
        ("Lady Gaga", ["art pop", "dance pop", "pop"], 93, 31000000, "Poker Face"),
        ("Miley Cyrus", ["pop", "pop rock"], 87, 28000000, "Flowers"),
        ("Bruno Mars", ["dance pop", "pop", "funk"], 94, 62000000, "Just the Way You Are"),
        ("Ed Sheeran", ["pop", "singer-songwriter", "uk pop"], 91, 115000000, "Shape of You"),
        ("Adele", ["british soul", "pop", "soul"], 88, 54000000, "Easy On Me"),
        ("Sam Smith", ["british soul", "dance pop", "pop"], 86, 25000000, "Unholy"),
        ("Sia", ["australian dance", "pop"], 85, 28000000, "Chandelier"),
        ("Camila Cabello", ["dance pop", "latin pop", "pop"], 84, 32000000, "Havana"),
        ("Selena Gomez", ["dance pop", "pop", "post-teen pop"], 85, 52000000, "Lose You to Love Me"),
        ("Demi Lovato", ["dance pop", "pop", "pop rock"], 80, 26000000, "Cool for the Summer"),
        ("Halsey", ["electropop", "indie pop", "pop"], 84, 23000000, "Without Me"),
        ("Lorde", ["art pop", "indie pop", "nz pop"], 83, 14000000, "Royals"),
        ("Lana Del Rey", ["art pop", "sadcore", "pop"], 93, 38000000, "Summertime Sadness"),
        ("Troye Sivan", ["australian pop", "dance pop", "pop"], 84, 7900000, "Rush"),
        ("Conan Gray", ["bedroom pop", "indie pop", "pop"], 82, 8200000, "Heather"),
        ("Tate McRae", ["dance pop", "pop"], 88, 6800000, "greedy"),
        ("Gracie Abrams", ["bedroom pop", "indie pop", "pop"], 87, 5200000, "I Love You, I'm Sorry"),
        ("Reneé Rapp", ["pop", "broadway pop", "alt-pop"], 81, 2400000, "Too Well"),
        ("Madison Beer", ["dance pop", "pop"], 82, 6900000, "Make You Mine"),
        ("Zara Larsson", ["dance pop", "pop", "swedish pop"], 81, 12000000, "Lush Life"),
        ("Bebe Rexha", ["dance pop", "pop", "electropop"], 83, 11000000, "I'm Good (Blue)"),
        ("Rita Ora", ["dance pop", "pop", "uk pop"], 79, 9400000, "Let You Love Me"),
        ("Ellie Goulding", ["dance pop", "electropop", "pop"], 81, 14000000, "Lights"),
        ("Meghan Trainor", ["dance pop", "pop", "post-teen pop"], 82, 15000000, "All About That Bass"),
        ("Kelly Clarkson", ["dance pop", "pop", "pop rock"], 78, 7100000, "Since U Been Gone"),
        ("P!nk", ["dance pop", "pop", "pop rock"], 82, 14000000, "Just Give Me a Reason"),
        ("Carly Rae Jepsen", ["dance pop", "electropop", "indie pop"], 78, 4800000, "Call Me Maybe"),
        ("Marina", ["art pop", "dance pop", "electropop"], 77, 4900000, "Primadonna"),
        ("Rina Sawayama", ["art pop", "dance pop", "hyperpop"], 75, 1400000, "XS"),
        ("Kim Petras", ["dance pop", "electropop", "hyperpop"], 78, 1600000, "Unholy"),
        ("Kesha", ["dance pop", "electropop", "pop"], 80, 11000000, "TiK ToK"),
        ("Ava Max", ["dance pop", "electropop", "pop"], 84, 11000000, "Sweet but Psycho"),
        ("Benson Boone", ["pop", "singer-songwriter", "pop rock"], 91, 6200000, "Beautiful Things"),
        ("Stephen Sanchez", ["pop", "retro soul", "singer-songwriter"], 83, 3100000, "Until I Found You"),
        ("Noah Cyrus", ["alt-pop", "indie pop", "singer-songwriter"], 77, 3400000, "July"),
        ("Alec Benjamin", ["alt-pop", "electropop", "pop"], 80, 5800000, "Let Me Down Slowly"),
        ("Jeremy Zucker", ["bedroom pop", "indie pop", "pop"], 78, 4100000, "comethru"),
        ("Lauv", ["electropop", "indie pop", "pop"], 82, 6900000, "I Like Me Better"),
        ("Chelsea Cutler", ["bedroom pop", "indie pop", "pop"], 75, 1600000, "this is how you fall in love"),
        ("Dean Lewis", ["australian pop", "pop", "singer-songwriter"], 80, 4200000, "Be Alright"),
        ("Lewis Capaldi", ["pop", "uk pop", "singer-songwriter"], 84, 14000000, "Someone You Loved"),
        ("James Arthur", ["pop", "singer-songwriter", "uk pop"], 83, 13000000, "Say You Won't Let Go"),
        ("Calum Scott", ["pop", "uk pop", "singer-songwriter"], 80, 6900000, "Dancing On My Own"),
        ("George Ezra", ["folk-pop", "pop", "uk pop"], 77, 4800000, "Shotgun"),
        ("Vance Joy", ["folk-pop", "indie folk", "pop"], 81, 5600000, "Riptide"),
        ("Hozier", ["folk-pop", "indie rock", "modern blues"], 92, 9800000, "Too Sweet"),
        ("Maggie Rogers", ["indie pop", "art pop", "folk-pop"], 77, 1900000, "Light On"),
        ("FLETCHER", ["alt-pop", "pop", "electropop"], 77, 1800000, "Undrunk"),
        ("Maisie Peters", ["indie pop", "pop", "uk pop"], 74, 940000, "Lost The Breakup"),
        ("Griff", ["alt-pop", "dance pop", "electropop"], 73, 620000, "Black Hole"),
        ("Remi Wolf", ["alt-pop", "bedroom pop", "indie pop"], 74, 880000, "Photo ID"),
        ("Djo", ["bedroom pop", "indie pop", "psychedelic pop"], 85, 3400000, "End of Beginning")
    ]
    for n, sg, p, f, tt in pop_data:
        artists.append(build_artist(n, "Pop", sg, p, f, tt))

    # 3. INDIE & ALTERNATIVE (~70 artists)
    indie_data = [
        ("Imagine Dragons", ["modern rock", "pop rock", "rock"], 91, 55000000, "Believer"),
        ("Coldplay", ["permanent wave", "pop rock", "post-britpop"], 92, 53000000, "Yellow"),
        ("Twenty One Pilots", ["modern rock", "rock", "pov indie"], 87, 28000000, "Stressed Out"),
        ("OneRepublic", ["pop rock", "pop", "modern rock"], 87, 21000000, "Counting Stars"),
        ("Maroon 5", ["pop", "pop rock"], 89, 44000000, "Sugar"),
        ("The Killers", ["modern rock", "alternative rock", "permanent wave"], 85, 12000000, "Mr. Brightside"),
        ("Arctic Monkeys", ["garage rock", "modern rock", "sheffield indie"], 90, 27000000, "Do I Wanna Know?"),
        ("Tame Impala", ["neo-psychedelic", "indie rock", "psychedelic pop"], 88, 15000000, "The Less I Know The Better"),
        ("Radiohead", ["art rock", "alternative rock", "oxford indie"], 86, 12000000, "Creep"),
        ("The 1975", ["modern alternative rock", "indie pop", "art pop"], 83, 9800000, "Somebody Else"),
        ("Clairo", ["bedroom pop", "indie pop", "lo-fi indie"], 85, 8200000, "Sofia"),
        ("Mitski", ["art pop", "indie rock", "brooklyn indie"], 87, 8600000, "My Love Mine All Mine"),
        ("Phoebe Bridgers", ["indie folk", "sadcore", "la indie"], 82, 4500000, "Motion Sickness"),
        ("boygenius", ["indie folk", "indie rock", "alt-country"], 80, 2100000, "Not Strong Enough"),
        ("Cigarettes After Sex", ["ambient pop", "dream pop", "shoegaze"], 86, 11000000, "Apocalypse"),
        ("TV Girl", ["indie pop", "lo-fi indie", "chillwave"], 85, 6800000, "Lovers Rock"),
        ("beabadoobee", ["bedpop", "indie pop", "grunge pop"], 80, 4900000, "Glue Song"),
        ("Men I Trust", ["canadian indie", "dream pop", "indie pop"], 79, 3200000, "Show Me How"),
        ("Beach House", ["dream pop", "baltimore indie", "indie rock"], 80, 4100000, "Space Song"),
        ("Mac DeMarco", ["slacker rock", "indie rock", "bedroom pop"], 82, 6200000, "Chamber of Reflection"),
        ("Wallows", ["indie pop", "modern rock", "la indie"], 80, 4200000, "Are You Bored Yet?"),
        ("Dominic Fike", ["indie pop", "alternative r&b", "pop rap"], 83, 5200000, "3 Nights"),
        ("Glass Animals", ["indie pop", "modern alternative rock", "oxford indie"], 82, 6500000, "Heat Waves"),
        ("Gorillaz", ["alternative rock", "art pop", "virtual band"], 84, 14000000, "Feel Good Inc."),
        ("The Strokes", ["garage rock revival", "indie rock", "post-punk revival"], 82, 8500000, "Last Nite"),
        ("Cage The Elephant", ["modern rock", "garage rock", "indie rock"], 81, 7900000, "Cigarette Daydreams"),
        ("Rex Orange County", ["bedroom pop", "indie pop", "neo-soul"], 80, 6800000, "Best Friend"),
        ("The Neighbourhood", ["modern rock", "indie pop", "alternative rock"], 86, 18000000, "Sweater Weather"),
        ("Foster the People", ["indie pop", "modern rock", "dance pop"], 79, 7200000, "Pumped Up Kicks"),
        ("Phoenix", ["french indie pop", "indie rock", "synthpop"], 75, 2800000, "1901"),
        ("Two Door Cinema Club", ["indie rock", "irish indie", "dance-punk"], 76, 3900000, "What You Know"),
        ("Young the Giant", ["indie rock", "modern rock", "cali indie"], 76, 2900000, "Cough Syrup"),
        ("Vampire Weekend", ["indie pop", "baroque pop", "nyc indie"], 77, 3400000, "A-Punk"),
        ("Florence + The Machine", ["art pop", "indie rock", "baroque pop"], 82, 9800000, "Dog Days Are Over"),
        ("Arcade Fire", ["indie rock", "canadian indie", "art rock"], 76, 3800000, "The Suburbs"),
        ("Foals", ["indie rock", "math rock", "modern rock"], 74, 2100000, "My Number"),
        ("Declan McKenna", ["indie pop", "glam rock", "uk indie"], 74, 1800000, "Brazil"),
        ("Sam Fender", ["heartland rock", "indie rock", "geordie indie"], 78, 2200000, "Seventeen Going Under"),
        ("Inhaler", ["dublin indie", "indie rock", "post-punk revival"], 73, 1100000, "My Honest Face"),
        ("The Backseat Lovers", ["indie rock", "salt lake city indie", "slacker rock"], 77, 1800000, "Kilby Girl"),
        ("Peach Pit", ["vancouver indie", "slacker rock", "indie pop"], 76, 1900000, "Alrighty Aphrodite"),
        ("Current Joys", ["slacker rock", "indie surf", "lo-fi indie"], 77, 2400000, "Kids"),
        ("Surf Curse", ["surf punk", "garage rock", "indie rock"], 78, 2900000, "Freaks"),
        ("Eyedress", ["lo-fi indie", "post-punk", "bedroom pop"], 79, 3100000, "Jealous"),
        ("Vacations", ["australian indie", "dream pop", "indie surf"], 77, 2600000, "Telephones"),
        ("Her's", ["liverpool indie", "dream pop", "jangle pop"], 78, 2400000, "What Once Was"),
        ("Mild High Club", ["psychedelic pop", "jazz pop", "slacker rock"], 76, 1800000, "Homage"),
        ("Unknown Mortal Orchestra", ["psychedelic rock", "neo-psychedelic", "lo-fi"], 75, 1600000, "So Good at Being in Trouble"),
        ("Alvvays", ["shoegaze", "jangle pop", "toronto indie"], 75, 1400000, "Archie, Marry Me"),
        ("Japanese Breakfast", ["art pop", "indie pop", "dream pop"], 74, 1100000, "Be Sweet"),
        ("Big Thief", ["indie folk", "indie rock", "brooklyn indie"], 77, 1600000, "Vampire Empire"),
        ("Snail Mail", ["indie rock", "bubblegrunge", "lo-fi"], 71, 780000, "Pristine"),
        ("Soccer Mommy", ["indie rock", "bedroom pop", "nashville indie"], 72, 820000, "Shotgun"),
        ("Lucy Dacus", ["indie rock", "indie folk", "singer-songwriter"], 74, 980000, "Night Shift"),
        ("Julien Baker", ["indie rock", "sadcore", "memphis indie"], 71, 650000, "Sprained Ankle"),
        ("Weyes Blood", ["chamber pop", "art pop", "psychedelic folk"], 74, 1100000, "Andromeda"),
        ("Angel Olsen", ["art pop", "freak folk", "indie rock"], 73, 980000, "Shut Up Kiss Me"),
        ("Sharon Van Etten", ["art pop", "indie rock", "brooklyn indie"], 72, 890000, "Seventeen"),
        ("King Krule", ["jazz fusion", "post-punk", "art pop"], 74, 1400000, "Easy Easy"),
        ("DIIV", ["shoegaze", "dream pop", "brooklyn indie"], 71, 740000, "Doused"),
        ("Slowdive", ["shoegaze", "dream pop", "ambient rock"], 76, 1800000, "Kisses"),
        ("Cocteau Twins", ["dream pop", "ethereal wave", "shoegaze"], 76, 2100000, "Cherry-coloured Funk"),
        ("The Cure", ["goth rock", "post-punk", "new wave"], 82, 9400000, "Boys Don't Cry"),
        ("Joy Division", ["post-punk", "manchester indie", "art rock"], 76, 4200000, "Love Will Tear Us Apart"),
        ("New Order", ["synthpop", "madchester", "post-punk"], 76, 3900000, "Blue Monday"),
        ("The Smiths", ["jangle pop", "post-punk", "manchester indie"], 81, 7800000, "There Is a Light That Never Goes Out"),
        ("Pixies", ["alternative rock", "boston rock", "indie rock"], 78, 5600000, "Where Is My Mind?"),
        ("Sonic Youth", ["noise rock", "alternative rock", "art rock"], 72, 2100000, "Teen Age Riot"),
        ("Neutral Milk Hotel", ["elephant 6", "indie folk", "lo-fi"], 71, 1400000, "In the Aeroplane Over the Sea"),
        ("Pavement", ["slacker rock", "indie rock", "lo-fi"], 71, 1200000, "Harness Your Hopes"),
        ("Modest Mouse", ["indie rock", "post-grunge", "pacific northwest indie"], 75, 3400000, "Float On")
    ]
    for n, sg, p, f, tt in indie_data:
        artists.append(build_artist(n, "Indie / Alternative", sg, p, f, tt))

    # 4. EDM & ELECTRONIC (~60 artists)
    edm_data = [
        ("Calvin Harris", ["dance pop", "edm", "electro house"], 91, 31000000, "Summer"),
        ("David Guetta", ["dance pop", "edm", "pop dance"], 92, 41000000, "Titanium"),
        ("The Chainsmokers", ["dance pop", "edm", "electropop"], 86, 21000000, "Closer"),
        ("Skrillex", ["brostep", "dubstep", "edm"], 83, 11000000, "Bangarang"),
        ("Martin Garrix", ["dutch edm", "edm", "progressive house"], 83, 17000000, "Animals"),
        ("Avicii", ["big room", "edm", "progressive house"], 87, 26000000, "Wake Me Up"),
        ("Daft Punk", ["electro", "filter house", "french house"], 85, 18000000, "Get Lucky"),
        ("Fred again..", ["club", "house", "uk dance"], 87, 3400000, "adore u"),
        ("John Summit", ["house", "tech house"], 82, 1400000, "Where You Are"),
        ("Dom Dolla", ["house", "tech house", "melbourne bounce"], 81, 1100000, "Rhyme Dust"),
        ("Fisher", ["australian dance", "house", "tech house"], 81, 2400000, "Losing It"),
        ("Peggy Gou", ["house", "indie dance", "korean electronic"], 80, 1600000, "(It Goes Like) Nanana"),
        ("Disclosure", ["deep house", "uk garage", "house"], 80, 4800000, "Latch"),
        ("ODESZA", ["chillwave", "indie electronica", "future bass"], 79, 2400000, "Say My Name"),
        ("Flume", ["future bass", "australian dance", "indie dance"], 78, 4200000, "Never Be Like You"),
        ("RÜFÜS DU SOL", ["australian dance", "indie dance", "live electronic"], 80, 2900000, "Innerbloom"),
        ("Deadmau5", ["electro house", "progressive house", "edm"], 76, 5200000, "Ghosts 'n' Stuff"),
        ("Illenium", ["melodic dubstep", "future bass", "edm"], 79, 2600000, "Takeaway"),
        ("Zedd", ["complextro", "edm", "pop dance"], 82, 11000000, "Clarity"),
        ("Marshmello", ["brostep", "edm", "pop dance"], 84, 38000000, "Happier"),
        ("Tiësto", ["big room", "dutch edm", "trance"], 86, 17000000, "The Business"),
        ("Alesso", ["progressive house", "dutch edm", "dance pop"], 80, 8900000, "Heroes"),
        ("Armin van Buuren", ["trance", "dutch edm", "progressive trance"], 78, 7400000, "Blah Blah Blah"),
        ("Hardwell", ["big room", "electro house", "dutch edm"], 76, 7800000, "Spaceman"),
        ("Swedish House Mafia", ["progressive house", "electro house", "edm"], 80, 6800000, "Don't You Worry Child"),
        ("Steve Aoki", ["electro house", "edm", "trap"], 79, 12000000, "Pursuit of Happiness"),
        ("Kygo", ["tropical house", "edm", "pop dance"], 84, 18000000, "Firestone"),
        ("Major Lazer", ["moombahton", "dance pop", "electropop"], 81, 14000000, "Lean On"),
        ("DJ Snake", ["trap", "electronic trap", "pop dance"], 83, 16000000, "Turn Down for What"),
        ("Diplo", ["electro house", "moombahton", "pop dance"], 80, 6400000, "On My Mind"),
        ("Galantis", ["dance pop", "pop dance", "swedish edm"], 79, 6200000, "Runaway (U & I)"),
        ("Alan Walker", ["electro house", "edm", "norwegian pop"], 83, 44000000, "Faded"),
        ("KSHMR", ["big room", "indian edm", "progressive house"], 75, 4100000, "Secrets"),
        ("San Holo", ["future bass", "indie electronica", "dutch edm"], 72, 1800000, "Light"),
        ("Madeon", ["electropop", "french house", "synthpop"], 73, 1400000, "Shelter"),
        ("Porter Robinson", ["complextro", "synthpop", "art pop"], 76, 1800000, "Sad Machine"),
        ("Gryffin", ["melodic house", "future bass", "edm"], 76, 2100000, "Feel Good"),
        ("SLANDER", ["melodic dubstep", "heaven trap", "edm"], 74, 1400000, "Love Is Gone"),
        ("Seven Lions", ["melodic dubstep", "trance", "future bass"], 73, 1100000, "First Time"),
        ("Subtronics", ["riddim", "dubstep", "bass music"], 75, 980000, "Griztronics"),
        ("Excision", ["brostep", "dubstep", "deathstep"], 74, 1600000, "Feel Something"),
        ("Rezz", ["midtempo bass", "dark techno", "canadian electronic"], 73, 940000, "Someone Else"),
        ("Alison Wonderland", ["trap", "future bass", "australian dance"], 72, 1100000, "Church"),
        ("Chris Lake", ["tech house", "bass house", "uk house"], 79, 1400000, "Turn Off The Lights"),
        ("Gorgon City", ["deep house", "uk garage", "tech house"], 75, 1800000, "Ready For Your Love"),
        ("CamelPhat", ["melodic techno", "progressive house", "deep house"], 76, 1600000, "Cola"),
        ("Meduza", ["deep groove house", "tech house", "dance pop"], 81, 3800000, "Piece Of Your Heart"),
        ("Vintage Culture", ["brazilian bass", "deep house", "tech house"], 78, 2200000, "In The Dark"),
        ("Sonny Fodera", ["house", "tech house", "vocal house"], 76, 980000, "Asking"),
        ("James Hype", ["tech house", "uk house", "speed garage"], 79, 1600000, "Ferrari"),
        ("Bicep", ["belfast electronic", "breakbeat", "uk techno"], 74, 1100000, "Glue"),
        ("Four Tet", ["microhouse", "folktronica", "intelligent dance music"], 75, 1400000, "Baby"),
        ("Jamie xx", ["uk garage", "future garage", "indie dance"], 76, 1800000, "Gosh"),
        ("Bonobo", ["downtempo", "trip hop", "ninja tune"], 75, 2400000, "Cirrus"),
        ("Caribou", ["indie electronic", "folktronica", "neo-psychedelic"], 73, 1100000, "Can't Do Without You"),
        ("Lane 8", ["deep melodic house", "chill house", "anjunadeep"], 74, 1200000, "Grapevine"),
        ("Elderbrook", ["indie dance", "deep house", "electropop"], 76, 1800000, "Cola"),
        ("Nora En Pure", ["deep melodic house", "swiss house", "chillout"], 72, 1100000, "Come With Me"),
        ("Ben Böhmer", ["melodic techno", "anjunadeep", "progressive house"], 74, 980000, "Beyond Beliefs"),
        ("Charlotte de Witte", ["acid techno", "peak time techno", "belgian electronic"], 76, 2600000, "Age of Love")
    ]
    for n, sg, p, f, tt in edm_data:
        artists.append(build_artist(n, "EDM / Electronic", sg, p, f, tt))

    # 5. ROCK & METAL (~60 artists)
    rock_data = [
        ("Linkin Park", ["alternative metal", "nu metal", "post-grunge"], 90, 31000000, "In the End"),
        ("Metallica", ["thrash metal", "speed metal", "hard rock"], 87, 28000000, "Enter Sandman"),
        ("Red Hot Chili Peppers", ["funk rock", "alternative rock", "cali rock"], 86, 29000000, "Californication"),
        ("Nirvana", ["grunge", "alternative rock", "seattle rock"], 85, 23000000, "Smells Like Teen Spirit"),
        ("Foo Fighters", ["alternative rock", "post-grunge", "modern rock"], 83, 14000000, "Everlong"),
        ("System of a Down", ["alternative metal", "nu metal", "political metal"], 85, 16000000, "Chop Suey!"),
        ("Green Day", ["pop punk", "punk rock", "permanent wave"], 85, 22000000, "Boulevard of Broken Dreams"),
        ("Bring Me The Horizon", ["metalcore", "post-hardcore", "modern rock"], 83, 7600000, "Can You Feel My Heart"),
        ("Slipknot", ["alternative metal", "nu metal", "groove metal"], 84, 13000000, "Duality"),
        ("Ghost", ["hard rock", "swedish metal", "heavy metal"], 80, 3800000, "Mary On A Cross"),
        ("Queens of the Stone Age", ["alternative rock", "stoner rock", "desert rock"], 78, 4100000, "No One Knows"),
        ("Bad Omens", ["metalcore", "modern metal", "post-screamo"], 80, 2200000, "Just Pretend"),
        ("Sleep Token", ["alternative metal", "prog metal", "post-metal"], 79, 1800000, "The Summoning"),
        ("Deftones", ["alternative metal", "nu metal", "shoegaze metal"], 84, 6900000, "Cherry Waves"),
        ("Avenged Sevenfold", ["heavy metal", "hard rock", "metalcore"], 80, 9800000, "Hail to the King"),
        ("Korn", ["alternative metal", "nu metal", "rap metal"], 82, 9400000, "Freak on a Leash"),
        ("Paramore", ["pop punk", "emo", "alt-pop rock"], 84, 10000000, "Misery Business"),
        ("My Chemical Romance", ["emo", "pop punk", "post-hardcore"], 82, 9500000, "Welcome to the Black Parade"),
        ("Fall Out Boy", ["pop punk", "emo pop", "modern rock"], 83, 14000000, "Sugar, We're Goin Down"),
        ("Blink-182", ["pop punk", "punk rock", "socal punk"], 83, 12000000, "All The Small Things"),
        ("Panic! At The Disco", ["emo pop", "baroque pop", "pop rock"], 82, 13000000, "High Hopes"),
        ("The Offspring", ["pop punk", "socal punk", "skate punk"], 80, 8400000, "You're Gonna Go Far, Kid"),
        ("Sum 41", ["pop punk", "skate punk", "canadian punk"], 77, 5600000, "In Too Deep"),
        ("Rise Against", ["melodic hardcore", "punk rock", "hardcore punk"], 76, 4200000, "Savior"),
        ("Jimmy Eat World", ["emo", "pop punk", "power pop"], 75, 3100000, "The Middle"),
        ("All Time Low", ["pop punk", "neon pop punk", "emo pop"], 76, 3800000, "Dear Maria, Count Me In"),
        ("Pierce The Veil", ["post-hardcore", "screamo", "emo"], 79, 4600000, "King For A Day"),
        ("Sleeping With Sirens", ["post-hardcore", "screamo", "emo"], 75, 3900000, "If You Can't Hang"),
        ("A Day To Remember", ["easycore", "metalcore", "pop punk"], 77, 4400000, "If It Means a Lot to You"),
        ("I Prevail", ["post-hardcore", "metalcore", "nu-metalcore"], 77, 2600000, "Hurricane"),
        ("Motionless In White", ["gothic metalcore", "industrial metal", "post-hardcore"], 77, 2400000, "Masterpiece"),
        ("Ice Nine Kills", ["theatrical metalcore", "symphonic metalcore", "screamo"], 75, 1400000, "A Grave Mistake"),
        ("Architects", ["uk metalcore", "progressive metalcore", "melodic hardcore"], 74, 1600000, "Animals"),
        ("Spiritbox", ["canadian metalcore", "progressive metalcore", "djent"], 75, 1200000, "Holy Roller"),
        ("Lorna Shore", ["deathcore", "symphonic deathcore", "blackened deathcore"], 74, 980000, "To the Hellfire"),
        ("Polyphia", ["instrumental rock", "math rock", "prog metal"], 75, 1400000, "Playing God"),
        ("Gojira", ["progressive death metal", "groove metal", "french metal"], 75, 2100000, "Stranded"),
        ("Mastodon", ["sludge metal", "progressive metal", "stoner rock"], 72, 1600000, "Blood and Thunder"),
        ("Tool", ["progressive metal", "art rock", "alternative metal"], 79, 4600000, "Schism"),
        ("Alice in Chains", ["grunge", "alternative metal", "seattle rock"], 80, 6800000, "Man in the Box"),
        ("Soundgarden", ["grunge", "alternative metal", "hard rock"], 78, 5400000, "Black Hole Sun"),
        ("Pearl Jam", ["grunge", "alternative rock", "classic rock"], 81, 11000000, "Alive"),
        ("Stone Temple Pilots", ["grunge", "alternative rock", "hard rock"], 77, 5200000, "Plush"),
        ("Rage Against The Machine", ["rap metal", "alternative rock", "funk metal"], 80, 7800000, "Killing In the Name"),
        ("Audioslave", ["supergroup", "hard rock", "alternative rock"], 79, 6400000, "Like a Stone"),
        ("Guns N' Roses", ["hard rock", "hair metal", "glam metal"], 84, 34000000, "Sweet Child O' Mine"),
        ("AC/DC", ["hard rock", "aussie rock", "classic rock"], 85, 32000000, "Back In Black"),
        ("Led Zeppelin", ["hard rock", "blues rock", "british invasion"], 81, 17000000, "Stairway to Heaven"),
        ("Queen", ["glam rock", "classic rock", "arena rock"], 87, 48000000, "Bohemian Rhapsody"),
        ("The Rolling Stones", ["classic rock", "british invasion", "blues rock"], 82, 19000000, "Paint It, Black"),
        ("Aerosmith", ["hard rock", "classic rock", "glam metal"], 80, 14000000, "Dream On"),
        ("Iron Maiden", ["heavy metal", "nwobhm", "speed metal"], 78, 9200000, "The Trooper"),
        ("Judas Priest", ["heavy metal", "speed metal", "hard rock"], 75, 5400000, "Painkiller"),
        ("Black Sabbath", ["heavy metal", "doom metal", "hard rock"], 77, 7600000, "Paranoid"),
        ("Ozzy Osbourne", ["heavy metal", "hard rock", "glam metal"], 78, 8600000, "Crazy Train"),
        ("Megadeth", ["thrash metal", "speed metal", "heavy metal"], 75, 5400000, "Symphony of Destruction"),
        ("Rammstein", ["neue deutsche harte", "industrial metal", "german rock"], 81, 11000000, "Du Hast"),
        ("Disturbed", ["alternative metal", "nu metal", "hard rock"], 81, 10000000, "Down with the Sickness"),
        ("Three Days Grace", ["post-grunge", "alternative metal", "hard rock"], 82, 11000000, "I Hate Everything About You"),
        ("Breaking Benjamin", ["post-grunge", "alternative metal", "hard rock"], 79, 6900000, "The Diary of Jane")
    ]
    for n, sg, p, f, tt in rock_data:
        artists.append(build_artist(n, "Rock / Metal", sg, p, f, tt))

    # 6. R&B & SOUL (~50 artists)
    rnb_data = [
        ("The Weeknd", ["canadian contemporary r&b", "canadian pop", "pop", "r&b"], 98, 92000000, "Blinding Lights"),
        ("SZA", ["contemporary r&b", "r&b", "pop"], 93, 27000000, "Kill Bill"),
        ("Frank Ocean", ["neo soul", "r&b", "indie r&b"], 88, 16000000, "Chanel"),
        ("Daniel Caesar", ["canadian contemporary r&b", "neo soul", "r&b"], 86, 12000000, "Best Part"),
        ("Brent Faiyaz", ["contemporary r&b", "dmv r&b", "r&b"], 86, 7800000, "Trust"),
        ("Summer Walker", ["contemporary r&b", "r&b"], 85, 8200000, "Playing Games"),
        ("Bryson Tiller", ["kentucky hip hop", "r&b", "trap soul"], 85, 8700000, "Don't"),
        ("Kali Uchis", ["colombian pop", "r&b", "neo-soul"], 88, 8900000, "telepatía"),
        ("Steve Lacy", ["afrofuturism", "indie r&b", "neo-soul"], 84, 7600000, "Bad Habit"),
        ("Childish Gambino", ["afrofuturism", "hip hop", "r&b"], 84, 14000000, "Redbone"),
        ("PARTYNEXTDOOR", ["canadian contemporary r&b", "r&b", "toronto rap"], 87, 8100000, "Break from Toronto"),
        ("Jhené Aiko", ["contemporary r&b", "r&b", "urban contemporary"], 84, 10000000, "Sativa"),
        ("Giveon", ["contemporary r&b", "r&b"], 82, 6400000, "Heartbreak Anniversary"),
        ("Kehlani", ["contemporary r&b", "r&b", "pop"], 83, 8900000, "Nights Like This"),
        ("H.E.R.", ["contemporary r&b", "r&b"], 81, 7100000, "Best Part"),
        ("Miguel", ["contemporary r&b", "r&b", "neo soul"], 82, 5900000, "Sure Thing"),
        ("Khalid", ["contemporary r&b", "pop", "electropop"], 84, 16000000, "Location"),
        ("6LACK", ["atl hip hop", "contemporary r&b", "r&b"], 80, 5400000, "PRBLMS"),
        ("Tory Lanez", ["canadian contemporary r&b", "melodic rap", "toronto rap"], 83, 7600000, "The Color Violet"),
        ("Chris Brown", ["contemporary r&b", "dance pop", "pop"], 88, 22000000, "Under The Influence"),
        ("Usher", ["contemporary r&b", "dance pop", "r&b"], 85, 14000000, "Yeah!"),
        ("Alicia Keys", ["contemporary r&b", "neo soul", "pop"], 83, 13000000, "If I Ain't Got You"),
        ("John Legend", ["neo soul", "pop", "urban contemporary"], 81, 14000000, "All of Me"),
        ("Ne-Yo", ["contemporary r&b", "dance pop", "pop"], 82, 8900000, "So Sick"),
        ("Trey Songz", ["contemporary r&b", "r&b"], 78, 6800000, "Bottoms Up"),
        ("Jeremih", ["chicago rap", "contemporary r&b", "r&b"], 79, 4600000, "Oui"),
        ("Ty Dolla $ign", ["cali rap", "pop rap", "r&b"], 84, 8200000, "Or Nah"),
        ("Ella Mai", ["contemporary r&b", "r&b", "uk contemporary r&b"], 79, 4400000, "Boo'd Up"),
        ("Snoh Aalegra", ["contemporary r&b", "neo soul", "swedish soul"], 78, 2600000, "I Want You Around"),
        ("Victoria Monét", ["contemporary r&b", "dance pop", "r&b"], 80, 2400000, "On My Mama"),
        ("Tinashe", ["contemporary r&b", "dance pop", "r&b"], 79, 3600000, "Nasty"),
        ("Jorja Smith", ["british soul", "neo soul", "uk contemporary r&b"], 78, 3800000, "Be Honest"),
        ("Mahalia", ["british soul", "neo soul", "uk contemporary r&b"], 74, 1600000, "Sober"),
        ("Cleo Sol", ["british soul", "neo soul", "uk contemporary r&b"], 76, 980000, "When I'm in Your Arms"),
        ("Arlo Parks", ["bedroom pop", "indie r&b", "neo-soul"], 72, 780000, "Eugene"),
        ("Raveena", ["indie r&b", "neo soul", "psychedelic soul"], 71, 680000, "If Only"),
        ("UMI", ["bedroom r&b", "indie r&b", "neo soul"], 73, 1100000, "Love Affair"),
        ("SiR", ["contemporary r&b", "neo soul", "r&b"], 76, 1400000, "D'Evils"),
        ("Lucky Daye", ["contemporary r&b", "neo soul", "new orleans soul"], 77, 1800000, "Roll Some Mo"),
        ("Leon Bridges", ["classic soul", "modern blues", "retro soul"], 80, 3600000, "Texas Sun"),
        ("Anderson .Paak", ["contemporary r&b", "funk", "oxnard indie"], 81, 4800000, "Come Down"),
        ("Thundercat", ["afrofuturism", "indie soul", "jazz funk"], 78, 2800000, "Funny Thing"),
        ("Masego", ["afrofuturism", "nu jazz", "trap house jazz"], 77, 2400000, "Tadow"),
        ("Tom Misch", ["indie soul", "neo-mellow", "uk pop"], 75, 1800000, "It Runs Through Me"),
        ("FKJ", ["french indie", "indie soul", "nu disco"], 76, 2100000, "Ylang Ylang"),
        ("Erykah Badu", ["afrofuturism", "neo soul", "urban contemporary"], 78, 4800000, "On & On"),
        ("Lauryn Hill", ["hip hop", "neo soul", "r&b"], 80, 5800000, "Doo Wop (That Thing)"),
        ("Sade", ["british soul", "quiet storm", "smooth soul"], 81, 5600000, "Smooth Operator"),
        ("D'Angelo", ["classic soul", "funk", "neo soul"], 74, 2100000, "Untitled (How Does It Feel)")
    ]
    for n, sg, p, f, tt in rnb_data:
        artists.append(build_artist(n, "R&B / Soul", sg, p, f, tt))

    # 7. LATIN & REGGAETON (~50 artists)
    latin_data = [
        ("Bad Bunny", ["reggaeton", "trap latino", "urbano latino"], 98, 88000000, "Monaco"),
        ("Peso Pluma", ["corridos tumbados", "musica mexicana", "sierreno"], 93, 19000000, "Ella Baila Sola"),
        ("J Balvin", ["reggaeton", "reggaeton colombiano", "urbano latino"], 88, 38000000, "Mi Gente"),
        ("Karol G", ["reggaeton", "reggaeton colombiano", "urbano latino"], 92, 42000000, "PROVENZA"),
        ("Rauw Alejandro", ["puerto rican pop", "reggaeton", "urbano latino"], 91, 21000000, "Todo De Ti"),
        ("Feid", ["colombian pop", "reggaeton", "urbano latino"], 92, 17000000, "LUNA"),
        ("Myke Towers", ["reggaeton", "trap latino", "urbano latino"], 89, 14000000, "LALA"),
        ("Shakira", ["colombian pop", "dance pop", "latin pop"], 89, 36000000, "Hips Don't Lie"),
        ("Bizarrap", ["argentine hip hop", "trap latino", "edm"], 87, 12000000, "Bzrp Music Sessions #53"),
        ("ROSALÍA", ["pop flamenco", "r&b en espanol", "urbano latino"], 86, 12000000, "DESPECHÁ"),
        ("Daddy Yankee", ["latin hip hop", "reggaeton", "urbano latino"], 87, 34000000, "Gasolina"),
        ("Ozuna", ["puerto rican pop", "reggaeton", "trap latino"], 86, 37000000, "Dile Que Tu Me Quieres"),
        ("Maluma", ["latin pop", "reggaeton", "reggaeton colombiano"], 85, 33000000, "Hawái"),
        ("Anuel AA", ["reggaeton", "trap boricua", "trap latino"], 88, 31000000, "Ella Quiere Beber"),
        ("Manuel Turizo", ["colombian pop", "latin pop", "reggaeton"], 84, 15000000, "La Bachata"),
        ("Carin Leon", ["banda", "musica mexicana", "norteno"], 87, 8900000, "Primera Cita"),
        ("Fuerza Regida", ["corridos tumbados", "musica mexicana", "sierreno"], 89, 9800000, "Harley Quinn"),
        ("Junior H", ["corridos tumbados", "musica mexicana", "sad sierreño"], 88, 8600000, "Fin de Semana"),
        ("Natanael Cano", ["corridos tumbados", "musica mexicana", "trap corridos"], 86, 7800000, "Amor Tumbado"),
        ("Eslabon Armado", ["corridos tumbados", "musica mexicana", "sierreno"], 85, 5400000, "Ella Baila Sola"),
        ("Grupo Frontera", ["cumbia norteña", "musica mexicana", "norteno"], 87, 8200000, "un x100to"),
        ("Christian Nodal", ["mariachi", "musica mexicana", "ranchera"], 84, 11000000, "Adiós Amor"),
        ("Arcángel", ["reggaeton", "trap latino", "urbano latino"], 84, 14000000, "La Jumpa"),
        ("Eladio Carrión", ["trap latino", "urbano latino", "puerto rican rap"], 85, 7800000, "Kemba Walker"),
        ("Mora", ["reggaeton", "trap latino", "urbano latino"], 85, 6200000, "LA INOCENTE"),
        ("Chencho Corleone", ["reggaeton", "urbano latino"], 83, 6800000, "Me Porto Bonito"),
        ("Sech", ["panamanian pop", "reggaeton", "urbano latino"], 81, 11000000, "Otro Trago"),
        ("Farruko", ["latin hip hop", "reggaeton", "trap latino"], 83, 19000000, "Pepas"),
        ("Nicky Jam", ["latin hip hop", "reggaeton", "trap latino"], 84, 25000000, "El Amante"),
        ("Don Omar", ["latin hip hop", "reggaeton", "urbano latino"], 83, 18000000, "Danza Kuduro"),
        ("Wisin & Yandel", ["latin hip hop", "reggaeton", "urbano latino"], 84, 16000000, "Algo Me Gusta De Ti"),
        ("Becky G", ["latin pop", "reggaeton", "urbano latino"], 83, 21000000, "MAMIII"),
        ("Natti Natasha", ["latin pop", "reggaeton", "urbano latino"], 80, 12000000, "Sin Pijama"),
        ("TINI", ["argentine pop", "latin pop", "post-teen pop"], 81, 9800000, "La_Original.mp3"),
        ("Emilia", ["argentine pop", "latin pop", "r&b argentino"], 83, 5600000, "No_Se_Ve.mp3"),
        ("Young Miko", ["puerto rican pop", "trap latino", "urbano latino"], 84, 4800000, "Classy 101"),
        ("Maria Becerra", ["argentine pop", "latin pop", "reggaeton"], 83, 8900000, "Automático"),
        ("Duki", ["argentine hip hop", "trap argentino", "trap latino"], 85, 11000000, "She Don't Give a FO"),
        ("Trueno", ["argentine hip hop", "freestyle", "trap argentino"], 82, 6400000, "REAL GANGSTA LOVE"),
        ("Tiago PZK", ["argentine pop", "latin pop", "r&b argentino"], 82, 5900000, "Entre Nosotros"),
        ("Quevedo", ["spanish hip hop", "trap latino", "urbano espanol"], 85, 7800000, "Columbia"),
        ("Morat", ["colombian pop", "latin pop", "pop rock"], 83, 9800000, "Besos En Guerra"),
        ("Sebastian Yatra", ["colombian pop", "latin pop", "reggaeton"], 82, 21000000, "Tacones Rojos"),
        ("Camilo", ["colombian pop", "latin pop"], 82, 17000000, "Vida de Rico"),
        ("Luis Fonsi", ["latin pop", "puerto rican pop"], 82, 19000000, "Despacito"),
        ("Enrique Iglesias", ["dance pop", "latin pop", "pop"], 82, 18000000, "Bailando"),
        ("Romeo Santos", ["bachata", "dominican pop", "latin pop"], 84, 21000000, "Propuesta Indecente"),
        ("Prince Royce", ["bachata", "latin pop"], 80, 14000000, "Darte un Beso"),
        ("Aventura", ["bachata", "dominican pop"], 84, 15000000, "Obsesión")
    ]
    for n, sg, p, f, tt in latin_data:
        artists.append(build_artist(n, "Latin / Reggaeton", sg, p, f, tt))

    # 8. COUNTRY & AMERICANA (~45 artists)
    country_data = [
        ("Morgan Wallen", ["contemporary country", "country"], 95, 16000000, "Last Night"),
        ("Zach Bryan", ["classic oklahoma country", "outlaw country"], 94, 9400000, "Something in the Orange"),
        ("Luke Combs", ["contemporary country", "country"], 90, 11000000, "Fast Car"),
        ("Chris Stapleton", ["contemporary country", "country", "outlaw country"], 87, 7800000, "Tennessee Whiskey"),
        ("Noah Kahan", ["folk-pop", "indie folk", "vermont indie"], 89, 7200000, "Stick Season"),
        ("Kacey Musgraves", ["classic texas country", "contemporary country"], 81, 3100000, "Slow Burn"),
        ("The Lumineers", ["denver indie", "folk-pop", "indie folk"], 83, 11000000, "Ophelia"),
        ("Tyler Childers", ["appalachian folk", "kentucky indie", "outlaw country"], 84, 3800000, "All Your'n"),
        ("Jelly Roll", ["country rap", "modern southern rock", "nashville sound"], 87, 4900000, "Need A Favor"),
        ("Bailey Zimmerman", ["contemporary country", "country"], 83, 3100000, "Rock and A Hard Place"),
        ("Kane Brown", ["contemporary country", "country pop"], 83, 8900000, "Heaven"),
        ("Sam Hunt", ["contemporary country", "country pop"], 79, 6400000, "Body Like A Back Road"),
        ("Cody Johnson", ["classic texas country", "contemporary country"], 81, 2900000, "Til You Can't"),
        ("Lainey Wilson", ["contemporary country", "country"], 82, 2600000, "Watermelon Moonshine"),
        ("HARDY", ["contemporary country", "country rock"], 81, 2100000, "TRUCK BED"),
        ("Ernest", ["contemporary country", "country"], 77, 980000, "Flower Shops"),
        ("Cole Swindell", ["contemporary country", "country"], 78, 3800000, "She Had Me At Heads Carolina"),
        ("Thomas Rhett", ["contemporary country", "country pop"], 80, 7100000, "Die a Happy Man"),
        ("Luke Bryan", ["contemporary country", "country pop"], 81, 13000000, "Play It Again"),
        ("Jason Aldean", ["contemporary country", "country road"], 80, 11000000, "Dirt Road Anthem"),
        ("Florida Georgia Line", ["bro-country", "contemporary country"], 80, 10000000, "Cruise"),
        ("Dan + Shay", ["contemporary country", "country pop"], 79, 7800000, "Tequila"),
        ("Russell Dickerson", ["contemporary country", "country pop"], 75, 1800000, "Yours"),
        ("Jordan Davis", ["contemporary country", "country pop"], 79, 2400000, "Buy Dirt"),
        ("Jon Pardi", ["contemporary country", "neo-traditional country"], 79, 3100000, "Head Over Boots"),
        ("Parker McCollum", ["classic texas country", "contemporary country"], 79, 1900000, "Burn It Down"),
        ("Warren Zeiders", ["contemporary country", "country rock"], 78, 1600000, "Pretty Little Poison"),
        ("Koe Wetzel", ["classic texas country", "texas country"], 81, 2100000, "High Road"),
        ("Colter Wall", ["canadian country", "outlaw country"], 78, 1900000, "Sleeping on the Blacktop"),
        ("Charley Crockett", ["gulf and western", "outlaw country"], 76, 940000, "Welcome to Hard Times"),
        ("Sturgill Simpson", ["alternative country", "outlaw country"], 77, 1800000, "Turtles All the Way Down"),
        ("Jason Isbell", ["alternative country", "americana", "roots rock"], 75, 1400000, "Cover Me Up"),
        ("Sierra Ferrell", ["alt-country", "americana", "bluegrass"], 76, 880000, "In Dreams"),
        ("Maren Morris", ["contemporary country", "country pop"], 77, 3600000, "The Bones"),
        ("Miranda Lambert", ["contemporary country", "country"], 78, 5900000, "Bluebird"),
        ("Carrie Underwood", ["contemporary country", "country pop"], 80, 11000000, "Before He Cheats"),
        ("Keith Urban", ["australian country", "contemporary country"], 79, 7800000, "Blue Ain't Your Color"),
        ("Kenny Chesney", ["contemporary country", "country"], 80, 9100000, "American Kids"),
        ("Blake Shelton", ["contemporary country", "country"], 79, 10000000, "God's Country"),
        ("Brad Paisley", ["contemporary country", "country"], 76, 5200000, "Whiskey Lullaby"),
        ("Tim McGraw", ["contemporary country", "country"], 80, 7800000, "Live Like You Were Dying"),
        ("George Strait", ["classic country", "traditional country"], 80, 7200000, "Amarillo By Morning"),
        ("Johnny Cash", ["classic country", "outlaw country", "rockabilly"], 81, 9800000, "Hurt"),
        ("Willie Nelson", ["classic country", "outlaw country", "roots rock"], 77, 5400000, "On the Road Again"),
        ("Dolly Parton", ["classic country", "country"], 78, 6800000, "Jolene")
    ]
    for n, sg, p, f, tt in country_data:
        artists.append(build_artist(n, "Country / Folk", sg, p, f, tt))

    # 9. K-POP & ASIAN POP (~45 artists)
    kpop_data = [
        ("BTS", ["k-pop", "k-pop boy group"], 92, 75000000, "Dynamite"),
        ("BLACKPINK", ["k-pop", "k-pop girl group"], 91, 51000000, "Pink Venom"),
        ("NewJeans", ["k-pop", "k-pop girl group"], 88, 14000000, "Super Shy"),
        ("TWICE", ["k-pop", "k-pop girl group"], 85, 22000000, "The Feels"),
        ("Stray Kids", ["k-pop", "k-pop boy group"], 88, 17000000, "Chk Chk Boom"),
        ("SEVENTEEN", ["k-pop", "k-pop boy group"], 86, 14000000, "MAESTRO"),
        ("ENHYPEN", ["k-pop", "k-pop boy group"], 85, 11000000, "Bite Me"),
        ("aespa", ["k-pop", "k-pop girl group"], 86, 7500000, "Supernova"),
        ("LE SSERAFIM", ["k-pop", "k-pop girl group"], 86, 8200000, "EASY"),
        ("TXT", ["k-pop", "k-pop boy group"], 83, 11000000, "Deja Vu"),
        ("ATEEZ", ["k-pop", "k-pop boy group"], 81, 6200000, "BOUNCY"),
        ("ITZY", ["k-pop", "k-pop girl group"], 81, 7400000, "WANNABE"),
        ("IVE", ["k-pop", "k-pop girl group"], 84, 5600000, "LOVE DIVE"),
        ("(G)I-DLE", ["k-pop", "k-pop girl group"], 84, 9800000, "Queencard"),
        ("NCT 127", ["k-pop", "k-pop boy group"], 79, 6400000, "Kick It"),
        ("NCT DREAM", ["k-pop", "k-pop boy group"], 80, 5800000, "Smoothie"),
        ("EXO", ["k-pop", "k-pop boy group"], 80, 11000000, "Love Shot"),
        ("Red Velvet", ["k-pop", "k-pop girl group"], 80, 9400000, "Psycho"),
        ("MAMAMOO", ["k-pop", "k-pop girl group"], 76, 5200000, "HIP"),
        ("STAYC", ["k-pop", "k-pop girl group"], 77, 3400000, "ASAP"),
        ("NMIXX", ["k-pop", "k-pop girl group"], 79, 3100000, "DASH"),
        ("RIIZE", ["k-pop", "k-pop boy group"], 80, 2400000, "Get A Guitar"),
        ("ZEROBASEONE", ["k-pop", "k-pop boy group"], 78, 1800000, "In Bloom"),
        ("BOYNEXTDOOR", ["k-pop", "k-pop boy group"], 78, 1600000, "Earth, Wind & Fire"),
        ("TREASURE", ["k-pop", "k-pop boy group"], 77, 4200000, "DARARI"),
        ("THE BOYZ", ["k-pop", "k-pop boy group"], 76, 2900000, "THRILL RIDE"),
        ("MONSTA X", ["k-pop", "k-pop boy group"], 76, 4800000, "Shoot Out"),
        ("GOT7", ["k-pop", "k-pop boy group"], 76, 6800000, "Just right"),
        ("SHINee", ["k-pop", "k-pop boy group"], 76, 3800000, "Ring Ding Dong"),
        ("BIGBANG", ["k-pop", "k-pop boy group"], 78, 5900000, "BANG BANG BANG"),
        ("IU", ["k-pop", "korean ballad", "k-pop solo"], 81, 9200000, "eight"),
        ("TAEYANG", ["k-pop", "k-pop solo", "korean r&b"], 78, 3800000, "VIBE"),
        ("TAEYEON", ["k-pop", "k-pop solo", "korean pop"], 77, 4400000, "To. X"),
        ("BIBI", ["k-rap", "korean r&b", "alt-kpop"], 80, 2800000, "Bam Yang Gang"),
        ("Jay Park", ["k-rap", "korean r&b"], 77, 3900000, "MOMMAE"),
        ("DPR IAN", ["korean r&b", "alt-pop", "australian r&b"], 81, 3100000, "Don't Go Insane"),
        ("DPR LIVE", ["k-rap", "korean r&b"], 75, 1800000, "Jasmine"),
        ("keshi", ["chill r&b", "bedroom pop", "asian-american pop"], 83, 4900000, "LIMBO"),
        ("Rich Brian", ["indonesian hip hop", "asian rap"], 77, 3200000, "Midsummer Madness"),
        ("Joji", ["lo-fi indie", "alternative r&b", "trip hop"], 86, 12000000, "Glimpse of Us"),
        ("NIKI", ["indonesian pop", "indie r&b"], 81, 4800000, "lowkey"),
        ("Fujii Kaze", ["j-pop", "japanese r&b", "city pop"], 82, 4200000, "Shinunoga E-Wa"),
        ("YOASOBI", ["j-pop", "anisong", "japanese pop"], 84, 6800000, "Idol"),
        ("Kenshi Yonezu", ["j-pop", "japanese rock", "anisong"], 81, 4900000, "KICK BACK"),
        ("Ado", ["j-pop", "vocaloid", "japanese rock"], 82, 4800000, "Show")
    ]
    for n, sg, p, f, tt in kpop_data:
        artists.append(build_artist(n, "K-Pop", sg, p, f, tt))

    # 10. AMBIENT & CLASSICAL (~30 artists)
    ambient_data = [
        ("Ludovico Einaudi", ["compositional ambient", "contemporary classical", "neo-classical"], 84, 4200000, "Experience"),
        ("Max Richter", ["compositional ambient", "contemporary classical", "post-minimalism"], 79, 1800000, "On the Nature of Daylight"),
        ("Hans Zimmer", ["soundtrack", "cinematic classical", "epic score"], 85, 5900000, "Time"),
        ("Brian Eno", ["ambient", "art rock", "drone"], 74, 1600000, "An Ending (Ascent)"),
        ("Ólafur Arnalds", ["neo-classical", "compositional ambient", "icelandic indie"], 76, 1100000, "Near Light"),
        ("Nils Frahm", ["compositional ambient", "neo-classical", "modern piano"], 73, 980000, "Says"),
        ("Aphex Twin", ["idm", "ambient techno", "braindance"], 76, 2100000, "Selected Ambient Works #3"),
        ("Boards of Canada", ["downtempo", "idm", "hauntology"], 74, 1400000, "Dayvan Cowboy"),
        ("Jon Hopkins", ["ambient techno", "idm", "microhouse"], 72, 890000, "Singularity"),
        ("Tycho", ["chillwave", "downtempo", "indie electronica"], 74, 1400000, "Awake"),
        ("Philip Glass", ["contemporary classical", "minimalism", "post-minimalism"], 71, 980000, "Metamorphosis: Two"),
        ("Ennio Morricone", ["soundtrack", "italian soundtrack", "cinematic classical"], 78, 2900000, "The Ecstasy of Gold"),
        ("John Williams", ["soundtrack", "hollywood score", "orchestral"], 79, 3100000, "Star Wars Main Theme"),
        ("Howard Shore", ["soundtrack", "cinematic classical"], 77, 1800000, "Concerning Hobbits"),
        ("Ramin Djawadi", ["soundtrack", "cinematic score"], 77, 2100000, "Light of the Seven"),
        ("Dustin O'Halloran", ["neo-classical", "soundtrack"], 73, 760000, "Opus 23"),
        ("Yann Tiersen", ["french contemporary classical", "neo-classical"], 76, 1800000, "Comptine d'un autre été"),
        ("Yiruma", ["korean classical", "modern piano"], 77, 2400000, "River Flows in You"),
        ("Ryuichi Sakamoto", ["ambient", "japanese classical", "electronic"], 75, 1600000, "Merry Christmas Mr. Lawrence"),
        ("Joe Hisaishi", ["japanese soundtrack", "ghibli soundtrack", "orchestral"], 80, 2800000, "One Summer's Day"),
        ("Sigur Rós", ["post-rock", "icelandic indie", "ambient pop"], 75, 2100000, "Hoppípolla"),
        ("Explosions in the Sky", ["post-rock", "cinematic instrumental"], 72, 1100000, "Your Hand in Mine"),
        ("Stars of the Lid", ["ambient", "drone", "space ambient"], 67, 340000, "A Meaningful Moment"),
        ("Tim Hecker", ["ambient", "noise", "deconstructed club"], 68, 420000, "Chimeras"),
        ("William Basinski", ["ambient", "tape loops", "drone"], 67, 380000, "The Disintegration Loops"),
        ("Carbon Based Lifeforms", ["ambient", "psychill", "downtempo"], 69, 520000, "World of Sleepers"),
        ("Solar Fields", ["ambient", "psychill", "gaming soundtrack"], 68, 460000, "Sol"),
        ("Marconi Union", ["ambient", "relaxation", "downtempo"], 68, 380000, "Weightless"),
        ("Kiasmos", ["minimal techno", "neo-classical", "ambient techno"], 72, 680000, "Blurred")
    ]
    for n, sg, p, f, tt in ambient_data:
        artists.append(build_artist(n, "Jazz / Classical", sg, p, f, tt))

    # 11. AFROBEATS & DANCEHALL (~30 artists)
    afro_data = [
        ("Burna Boy", ["afrobeats", "afropop", "nigerian pop"], 89, 14000000, "Last Last"),
        ("Wizkid", ["afrobeats", "afropop", "nigerian pop"], 86, 12000000, "Essence"),
        ("Rema", ["afrobeats", "afrorave", "nigerian pop"], 88, 8900000, "Calm Down"),
        ("Tems", ["afrobeats", "alté", "nigerian pop"], 85, 4800000, "Free Mind"),
        ("Asake", ["afrobeats", "amapiano", "street pop"], 84, 3800000, "Lonely At The Top"),
        ("Ayra Starr", ["afrobeats", "afropop", "nigerian pop"], 86, 4200000, "Rush"),
        ("Davido", ["afrobeats", "afropop", "nigerian pop"], 84, 11000000, "FEEL"),
        ("Omah Lay", ["afrobeats", "afro soul", "nigerian pop"], 82, 3800000, "soso"),
        ("Fireboy DML", ["afrobeats", "afro soul", "nigerian pop"], 81, 3900000, "Peru"),
        ("CKay", ["afrobeats", "afropop"], 80, 4800000, "love nwantiti"),
        ("Oxlade", ["afrobeats", "afro soul"], 77, 2100000, "KU LO SA"),
        ("Tiwa Savage", ["afrobeats", "afropop", "nigerian pop"], 78, 6200000, "Somebody's Son"),
        ("Ruger", ["afrobeats", "dancehall", "nigerian pop"], 78, 2200000, "Asiwaju"),
        ("Victony", ["afrobeats", "afropop"], 77, 1800000, "Soweto"),
        ("Adekunle Gold", ["afro soul", "afrobeats", "nigerian pop"], 77, 2900000, "Party No Dey Stop"),
        ("Kizz Daniel", ["afrobeats", "afropop"], 79, 3600000, "Buga (Lo Lo Lo)"),
        ("Sean Paul", ["dancehall", "pop rap", "reggae fusion"], 83, 11000000, "Temperature"),
        ("Popcaan", ["dancehall", "jamaican pop"], 76, 2600000, "Silence"),
        ("Koffee", ["dancehall", "roots reggae", "reggae fusion"], 75, 1800000, "Toast"),
        ("Shenseea", ["dancehall", "jamaican pop"], 77, 2400000, "Blessed"),
        ("Vybz Kartel", ["dancehall", "reggae fusion"], 77, 3400000, "Fever"),
        ("Damian Marley", ["roots reggae", "reggae fusion"], 76, 3800000, "Welcome To Jamrock"),
        ("Bob Marley & The Wailers", ["roots reggae", "reggae"], 84, 19000000, "Three Little Birds"),
        ("Major League Djz", ["amapiano", "south african house"], 74, 1100000, "Bakwa Lah"),
        ("Uncle Waffles", ["amapiano", "south african house"], 75, 980000, "Tanzania"),
        ("Kabza De Small", ["amapiano", "south african house"], 76, 1600000, "Asibe Happy"),
        ("DJ Maphorisa", ["amapiano", "gqom", "south african house"], 76, 1800000, "Ba Straata")
    ]
    for n, sg, p, f, tt in afro_data:
        artists.append(build_artist(n, "Afrobeats / Dancehall", sg, p, f, tt))

    # Deduplicate by ID just in case
    unique_artists = {}
    for a in artists:
        if a["id"] not in unique_artists:
            unique_artists[a["id"]] = a

    result = list(unique_artists.values())
    print(f"Generated {len(result)} comprehensive catalog artists.")
    return result

if __name__ == "__main__":
    cat = get_550_artist_catalog()
    print("Sample artist:", cat[0]["name"], cat[0]["macro_genre"], len(cat[0]["genres"]))
